// <auto-generated />
namespace Zen.Tracker.Server.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TodoItemUserScoping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TodoItemUserScoping));
        
        string IMigrationMetadata.Id
        {
            get { return "201701012113474_TodoItemUserScoping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
